### ISSUE TITLE
errors in the header- line 43 and 659

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/affluent-lite#9]
We just received these error messages (listed below) in the header of our website as well as in the header of our WP dashboard. 

----Errors----------------
Deprecated: Required parameter $args follows optional parameter $depth in /var/www/wp-content/themes/affluent/core/classes/class_menu.php on line 43

Deprecated: Required parameter $output follows optional parameter $depth in /var/www/wp-content/themes/affluent/core/classes/class_menu.php on line 43

Deprecated: Required parameter $class follows optional parameter $taxonomy in /var/www/wp-content/themes/affluent/core/markup.php on line 659

https://support.wpchill.com/conversation/1629?folder_id=59

**Comment by cristianraiber** [comment]
Theme is no longer supported.
